### ISSUE TITLE
Support vanish plugins

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/AzLink#10]
Hi,

I noticed that **AzLink** does not support Vanish plugins _(CMI/Essentials/SuperVanish & PremiumVanish_).
I find this very annoying, so that's why I'm posting my suggestion here!

**Comment by Maxlego08** [comment]
Are you talking about displaying the number of players online?

**Comment by NoltoxGit** [comment]
> Are you talking about displaying the number of players online?

Yeah, I'm talking about the online players displayed on the site.

**Comment by MrMicky-FR** [comment]
Hi, support for Essentials vanish should be added in the next update 😃 It might also work with CMI and PremiumVanish but as these are paid plugins I can’t test.

**Comment by NoltoxGit** [comment]
> Hi, support for Essentials vanish should be added in the next update 😃 It might also work with CMI and PremiumVanish but as these are paid plugins I can’t test.

For CMI, ask if they have an API for that, and for PremiumVanish, I think it's the same as SuperVanish. ^^

**Comment by MrMicky-FR** [comment]
You can now enable this option in the config: https://github.com/Azuriom/AzLink/blob/efde73a8553cbf458eaff17b2fde5fe271c4638a/bukkit/src/main/resources/config.yml#L5-L8

It a plugin-independent solution that works with Essentials, and certainly some other plugins but I don’t really want to support each vanish plugin individually using their api

**Comment by NoltoxDev** [comment]
Hello !
I updated AzLink on my server, and so the .yml file appeared, I set the value to true and here are the errors it makes when the server starts:
`>.... [10:39:00 WARN]: [AzLink] Task #3863 for AzLink v1.0.2 generated an exception
java.lang.IllegalStateException: ServerPingEvent may only be triggered asynchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:610) ~[patched_1.16.5.jar:git-Paper-794]
at com.azuriom.azlink.bukkit.AzLinkBukkitPlugin.getOnlinePlayers(AzLinkBukkitPlugin.java:133) ~[?:?]
at com.azuriom.azlink.common.AzLinkPlugin.getServerData(AzLinkPlugin.java:147) ~[?:?]
at com.azuriom.azlink.common.tasks.FetcherTask.lambda$run$1(FetcherTask.java:40) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
at java.lang.Thread.run(Thread.java:831) [?:?]`

### INFORMATIONS
Server version: Paper 1.16.5 794
Plugin version: AzLink 1.0.2
